name: Generate Snake

# Triggers the workflow on a schedule and via manual dispatch
on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    # Defines the environment where the job will run
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository to the runner
      - uses: actions/checkout@v2

      # Generates the snake contribution graph
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: SudharakaA
          # Output files
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Display git status for debugging
      - name: Show Git Status
        run: git status

      # Push the changes back to the repository
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
